### ISSUE TITLE
关于fofa采集问题

### ISSUE THREAD

**Issue by huitc** [DropsDevopsOrg/ECommerceCrawlers#1]
https://github.com/DropsDevopsOrg/ECommerceCrawlers/tree/master/OthertCrawler/0x08fofa
我可以只導出IP/hostname么？。。。且不用json格式。。😅😅😃

**Comment by Hatcat123** [comment]
采集ip可以将50行中的find内容改为(.list_sx1 li a)，然后写入txt中吧！

**Comment by huitc** [comment]
用这个有可能能夠正常使用Fofa_spider.py么？
termux: https://play.google.com/store/apps/details?id=com.termux

**Comment by huitc** [comment]
最好附上教學谢~ (真的小白啦干。。。😅😅

**Comment by Hatcat123** [comment]
> 用这个有可能能够正常使用Fofa_spider.py么？
> termux：[https](https://play.google.com/store/apps/details?id=com.termux)：[//play.google.com/store/apps/details](https://play.google.com/store/apps/details?id=com.termux)？id [=](https://play.google.com/store/apps/details?id=com.termux) com.termux[](https://play.google.com/store/apps/details?id=com.termux)

termux中安装python能够实现。此程序采用模拟浏览器的方式爬取，将不能在手机中流畅运行此程序。

**Comment by huitc** [comment]
https://github.com/DropsDevopsOrg/ECommerceCrawlers/issues/1#issuecomment-502468088

> 将50行中的find内容

??? ^^''

**Comment by huitc** [comment]
像這樣？
90行
```
                'url': item.find('.list_sx1 li a').text(),
```

**Comment by huitc** [comment]
"默认只显示一年内的数据，点击 all 链接查看所有。"
有選項是可以显示all的么???

**Comment by huitc** [comment]
还有93行`博彩`是什么?...
https://github.com/DropsDevopsOrg/ECommerceCrawlers/blob/master/OthertCrawler/0x08fofa/Fofa_spider.py#L93

**Comment by huitc** [comment]
真的小白啦......... t.t

**Comment by Hatcat123** [comment]
https://github.com/DropsDevopsOrg/ECommerceCrawlers/issues/1#issuecomment-502602781
这个是fofa的查询语法
