### ISSUE TITLE
大神帮忙看看这个是什么错?

### ISSUE THREAD

**Issue by dreamworkdw** [DropsDevopsOrg/ECommerceCrawlers#18]
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

**Comment by Hatcat123** [comment]
chrome服务以外的退出，状态码为1。因为我从你提供的信息中找不到任何运行环境或上下文的描述。只能猜测像这种情况大多是selenium与chromedriver版本不对应。或许你可以描述下现在做的事情，如运行那个程序，使用的工具、三方库版本号，运行到哪一步出错，在尝试重启电脑后仍然出现这样的错误……等等吧

**Comment by dreamworkdw** [comment]
感谢回复， 我在pycharm尝试运行toutiao_demo.py 这个脚本， 运行过程中提示我未添加chromedriver到Path， 我在win 环境修改PATH 添加Chromedirver后，运行脚本报如上错误， selenium版本为selenium-3.141.0
与chromedriver 版本为ChromeDriver 77.0.3865.40。

**Comment by Hatcat123** [comment]
@liangweiyang 或许你们能在一起讨论交流下。 @dreamworkdw 能否留下你的邮箱在这层评论中

**Comment by Hatcat123** [comment]
我尝试运行我的版本是
Name: selenium
Version: 3.14.0
ChromeDriver 2.40.565498
我给个建议：
或许你可以尝试给https://github.com/DropsDevopsOrg/ECommerceCrawlers/blob/29e34039adb9c981b6e111bf0c3f243f0ccf2ecd/OthertCrawler/0x12toutiao/toutiao_demo.py#L9
加上指定的路径path='xxx.exe'
或者重新下载chromium [chromedriver](http://chromedriver.storage.googleapis.com/index.html)
