### ISSUE TITLE
我的mongoDB开启账号密码认证过后程序无法启动

### ISSUE THREAD

**Issue by jimbirthday** [DropsDevopsOrg/ECommerceCrawlers#31]
我测试过本地无密码可登陆
服务器无密码可登陆.
可是当我连接服务器mongo用账号密码认证时,程序无法启动(mongo端口也不一样)
![image](https://user-images.githubusercontent.com/38313933/68082199-9dd1ef80-fe54-11e9-8898-f265e73cf566.png)

![image](https://user-images.githubusercontent.com/38313933/68082225-f86b4b80-fe54-11e9-9b8c-c26712f65e42.png)

**Comment by jimbirthday** [comment]
我尝试过你说的方法.但还是无法连接上


这是我的连接代码
![image](https://user-images.githubusercontent.com/38313933/68082853-ccec5f00-fe5c-11e9-9b22-f7e2808a2a80.png)


这是mongo账号
![image](https://user-images.githubusercontent.com/38313933/68082809-40da3780-fe5c-11e9-9e80-99b5d08d6fb6.png)

这是报错

![image](https://user-images.githubusercontent.com/38313933/68082858-d5dd3080-fe5c-11e9-9319-b4167be3b363.png)

**Comment by Hatcat123** [comment]
如果想要增加验证可以使用
```
self.db = conn.News
self.db.authenticate("account", "password")
```
你提供的信息太少，不能确定你最终在那一部分出现了错误。如果你仍然不能解决，请提供更多的报错信息与环境信息。
good lucky！

**Comment by Hatcat123** [comment]
```
self.db = conn.News
self.db.authenticate("account", "password")
```
你在这里少了db，请检查你的代码。
