### ISSUE TITLE
无法得到用户信息

### ISSUE THREAD

**Issue by Tianyu97** [DropsDevopsOrg/ECommerceCrawlers#40]
![image](https://user-images.githubusercontent.com/41757571/77009428-47b2a400-693e-11ea-9a0d-a0033e055d07.png)
运行search_by_db.py后关于用户的信息都是空的怎么解决呢？

**Comment by Hatcat123** [comment]
很抱歉，你提供的信息太少，不能为你提供有效准确的解决方式。
或许你可以尝试以下的方式解决：

1、 首先查看爬虫采集是否能采集到数据。
2、 再判断数据清洗得到的结果
3、是否因为采集频繁导致ip禁止访问。可以尝试代理。
4、插入数据库是否有错。
以上都会可能产生你提交的错误。

**Comment by Tianyu97** [comment]
是不是github上的代码没有传完整呢?我的运行顺序是这样的:
python model.py
python create_task.py
python search_by_db.py
我发现这三个文件里面并没有写入用户信息is_V, sex, area等相关代码. 没有办法得到2readme.md里的结果展示的数据啊...
![image](https://user-images.githubusercontent.com/41757571/77029471-25d31480-6972-11ea-800c-eaedbf892b82.png)
