### ISSUE TITLE
WeiboCrawler爬虫是不是没有源码了？

### ISSUE THREAD

**Issue by Aohanseven** [DropsDevopsOrg/ECommerceCrawlers#41]
WeiboCrawler爬虫是不是没有源码了
里面只有readme.md了

**Comment by Hatcat123** [comment]
[https://github.com/DropsDevopsOrg/ECommerceCrawlers/tree/master/WeiboCrawler](https://github.com/DropsDevopsOrg/ECommerceCrawlers/tree/master/WeiboCrawler)
