### ISSUE TITLE
fofa導出建议:

### ISSUE THREAD

**Issue by Hatcat123** [DropsDevopsOrg/ECommerceCrawlers#5]
fofa導出建议:
導出格式: `{http://|https://}(可選){ip|hostname}{:port}}(可選)`

_Originally posted by @huitc in https://github.com/DropsDevopsOrg/ECommerceCrawlers/issues/4#issuecomment-508130943_

**Comment by Joynice** [comment]
谢谢，会及时更新。

**Comment by huitc** [comment]
一般注册会员只能查5页
建議使用...(等

还有问一下是否要"all"
`是否默认只显示一年内的数据，点击 all 链接查看所有。`

**Comment by Hatcat123** [comment]
> fofa導出建议:
> 導出格式: `{http://|https://}(可選){ip|hostname}{:port}}(可選)`
> 
> _Originally posted by @huitc in [#4 (comment)](https://github.com/DropsDevopsOrg/ECommerceCrawlers/issues/4#issuecomment-508130943)_

https://github.com/DropsDevopsOrg/ECommerceCrawlers/blob/master/OthertCrawler/0x08fofa/Fofa_spider.py#L98
