### ISSUE TITLE
大众点评地址

### ISSUE THREAD

**Issue by Y3PM** [DropsDevopsOrg/ECommerceCrawlers#7]
您好，点评详情页，都是小方块，不知道您那边能不能破解掉，多谢多谢

**Comment by Joynice** [comment]
我们曾经遇到过这种情况，原因是使用Ubuntu Server版本，系统没有中文字体，导致爬下来的都是小方块，如果您也是这种原因，可以导入中文字体，如果是代码问题，我们及时更新，谢谢您的issus。

**Comment by safin1120** [comment]
您好，AssertionError问题怎么解决啊？assert css_links_link那里一直报错

**Comment by Hatcat123** [comment]
> 您好，AssertionError问题怎么解决啊？assert css_links_link那里一直报错

这里查看源码中assert_link 。如果接口没变，会返回一个列表。我根据当时返回列表的内容进行修改的。列表中返回的值一个是对的 一个是错的，而且每次爬取不同的内容的时候还不一样。我们的程序可能就提供一个大概是思路，或者讲解了字体库的思路。
