### ISSUE TITLE
闲鱼已经不能爬了吗？

### ISSUE THREAD

**Issue by brucelian** [DropsDevopsOrg/ECommerceCrawlers#9]

**Comment by Hatcat123** [comment]
明天看下，并更新下使用文档。

**Comment by Hatcat123** [comment]
> 明天看下，并更新下使用文档。

核心依然能使用。2019-7-27

**Comment by dagege1993** [comment]
今天测试好像已经不行了,接口已经封了

**Comment by Hatcat123** [comment]
> 今天测试好像已经不行了,接口已经封了

@dagege是的！非常抱歉我们失去了一个很好的接口。或许以后将不会再有很方便的接口使用。我们将会从其他地方找到类似的接口！！！

**Comment by taurusbb** [comment]
你好，请问有闲鱼最新的解决方法了吗？
